//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Info_employees = new HashSet<Info_employees>();
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int employee_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string rights { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string address_city { get; set; }
        public string home_address { get; set; }
        public string marital_status { get; set; }
        public string gender { get; set; }
        public Nullable<int> amount_children { get; set; }
        public string data_passport { get; set; }
        public string number_of_telephone { get; set; }
        public Nullable<System.DateTime> date_reg_passport { get; set; }
        public string organisation_passport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info_employees> Info_employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
