//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_accounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personal_accounting_DBEntities : DbContext
    {
        private static personal_accounting_DBEntities _context;
        public personal_accounting_DBEntities()
            : base("name=personal_accounting_DBEntities")
        {
        }
        public static personal_accounting_DBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new personal_accounting_DBEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departaments> Departaments { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Info_employees> Info_employees { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<State_time> State_time { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
    }
}
