//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_time
    {
        public int state_unit_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> departament_id { get; set; }
        public Nullable<int> quantity_state_unit { get; set; }
    
        public virtual Departaments Departaments { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
