//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations
    {
        public int vacation_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<System.DateTime> date_start_vacation { get; set; }
        public Nullable<int> quantity_day { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
